language: java
jdk:
  - openjdk11

branches:
  only:
    - master

script: "./gradlew clean build"

before_install:
  - chmod +x ./gradlew

cache:
  directories:
    - '$Home/ .m2/repository'
    - '$Home/ .gradle'



# CI 실행 완료 시 메일로 알람.
notifications:
  email:
    recipients:
      - kimtaejun9705@gmail.com